### ISSUE TITLE
preparing the dataset uwb atcc: ValueError with n_train, n_test = _validate_shuffle_split

### ISSUE THREAD

**Issue by sarranetor** [idiap/w2v2-air-traffic#2]
I extracted the uwb_atcc database ens extracted it in ZCU_CZ_ATC, putting wav file in audio folder and others in transcripts folder. I run the bash script:

bash data/databases/uwb_atcc/data_prepare_uwb_atcc_corpus.sh

there were 0 empty or blank utterances
printing the text file in: experiments/data/uwb_atcc/prep/text2_raw_spk
printing the text and tags file in: experiments/data/uwb_atcc/prep/utt2speakerid

Traceback (most recent call last):
  File "data/utils/gen_train_test.py", line 61, in <module>
    main()
  File "data/utils/gen_train_test.py", line 42, in main
    x_train, x_test = train_test_split(
  File "/home/liv/Developer/venv3.8-tf2/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/home/liv/Developer/venv3.8-tf2/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=None and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.

what can it be? I am not sure?

**Comment by JuanPZuluaga** [comment]
Hello! 

Sorry for taking so much time to reply. Could you put here the output of experiments/data/uwb_atcc/prep/text2_raw_spk?

It looks like the dataset is not getting correctly prepared at some point. That's probably why you're getting that error about '0' samples. 

Pablo

**Comment by damnfarooq** [comment]
I am getting the same error as sarranetor on VScode.

Although on Google colab this is what i got:
Empty utterance: uwb-atcc_APP-O8f26B_000225_000353 uwb-atcc_APP-O8f26B 2.260 3.530 [air]
Empty utterance: uwb-atcc_TWR-JfoHJv_000234_000308 uwb-atcc_TWR-JfoHJv 2.340 3.080 [air]
Empty utterance: uwb-atcc_TWR-VIKx0e_000309_000408 uwb-atcc_TWR-VIKx0e 3.090 4.080 [air]
Empty utterance: uwb-atcc_TWR-v1sw0a_002796_002867 uwb-atcc_TWR-v1sw0a 27.960 28.670 [air]
Empty utterance: uwb-atcc_TWR-q2wbS3_000336_000419 uwb-atcc_TWR-q2wbS3 3.360 4.190 [air]
Empty utterance: uwb-atcc_TWR-ZfmGUj_002451_002578 uwb-atcc_TWR-ZfmGUj 24.510 25.780 [ground]
Empty utterance: uwb-atcc_ACCU-OvZN8g_001321_001433 uwb-atcc_ACCU-OvZN8g 13.210 14.330 [ground]
there were 492 empty or blank utterances
printing the text file in: experiments/data/uwb_atcc/prep/text2_raw_spk
printing the text and tags file in: experiments/data/uwb_atcc/prep/utt2speakerid
printing the TRAIN SET IDS file in: experiments/data/uwb_atcc/train/ids
printing the TEST SET IDS file in: experiments/data/uwb_atcc/test/ids
creating the train folder:
creating the test folder:
UWB-ATCC corpus was sucessfully created

but the next bash gave error as follows:

!bash /content/drive/MyDrive/w2v2-air-traffic/ablations/uwb_atcc/train_w2v2_base.sh

Vocabulary is empty, you passed config/vocab.json
We will create a new vocabulary from the training+test file
*** About to start the training ***
*** output folder: experiments/results/baselines/wav2vec2-base/uwb_atcc/0.0ld_0.0ad_0.0attd_0.0fpd_0.01mtp_12mtl_0.0mfp_12mfl_2acc/ ***
python3: can't open file '/content/drive/MyDrive/w2v2-air-traffic/data/src/run_speech_recognition_ctc.py': [Errno 2] No such file or directory
Done training of baseline model for UWB-ATCC database

**Comment by damnfarooq** [comment]
Please help me fix the issue

**Comment by JuanPZuluaga** [comment]
Hello, 

I think the error might be here: 

https://github.com/idiap/w2v2-air-traffic/blob/25b91bfc1975d749bdad76bd6bd3b73cc140b2f7/src/run_asr_fine_tuning.sh#L18

Could you modify that value to:

`cmd=""`

And let me know what is the output?

**Comment by damnfarooq** [comment]
Yeah sure, give me 5 minutes

**Comment by damnfarooq** [comment]
I cant believe it actually worked damnn!!! I would have taken years to solve this issue, Thanks means a lot;
This is the output I obtained, expected 492 EMPTY UTTERANCES?
...
..
Empty utterance: uwb-atcc_APP-ZWCH4J_024924_025001 uwb-atcc_APP-ZWCH4J 249.240 250.010 [air]
Empty utterance: uwb-atcc_ACCU-bNGNLz_003137_003210 uwb-atcc_ACCU-bNGNLz 31.370 32.100 [air]
Empty utterance: uwb-atcc_ACCU-bNGNLz_003286_003369 uwb-atcc_ACCU-bNGNLz 32.860 33.690 [air]
Empty utterance: uwb-atcc_ACCU-bNGNLz_007525_007604 uwb-atcc_ACCU-bNGNLz 75.250 76.040 [air]
Empty utterance: uwb-atcc_TWR-yGF8s5_001233_001335 uwb-atcc_TWR-yGF8s5 12.330 13.350 [ground]
Empty utterance: uwb-atcc_TWR-m8CuYQ_001384_001432 uwb-atcc_TWR-m8CuYQ 13.840 14.320 [ground]
Empty utterance: uwb-atcc_APP-oDje3J_000356_000642 uwb-atcc_APP-oDje3J 3.560 6.420 [air]
Empty utterance: uwb-atcc_ACCU-y5UHTs_001414_001489 uwb-atcc_ACCU-y5UHTs 14.140 14.890 [air]
Empty utterance: uwb-atcc_ACCU-WGx5qF_001133_001227 uwb-atcc_ACCU-WGx5qF 11.330 12.270 [air]
Empty utterance: uwb-atcc_APP-sgKjJz_000308_000379 uwb-atcc_APP-sgKjJz 3.080 3.790 [air]
Empty utterance: uwb-atcc_ACCU-QfXh8b_001887_002017 uwb-atcc_ACCU-QfXh8b 18.870 20.170 [air]
Empty utterance: uwb-atcc_ACCU-hh8aIj_002189_002308 uwb-atcc_ACCU-hh8aIj 21.890 23.080 [air]
Empty utterance: uwb-atcc_TWR-mDzIBi_005798_005958 uwb-atcc_TWR-mDzIBi 57.980 59.580 [ground]
Empty utterance: uwb-atcc_TWR-mDzIBi_006064_006149 uwb-atcc_TWR-mDzIBi 60.640 61.490 [air]
Empty utterance: uwb-atcc_APP-wBCMEy_000319_000823 uwb-atcc_APP-wBCMEy 3.190 8.230 [ground]
Empty utterance: uwb-atcc_APP-wBCMEy_000973_001205 uwb-atcc_APP-wBCMEy 9.730 12.050 [air]
Empty utterance: uwb-atcc_TWR-952cUz_000760_000853 uwb-atcc_TWR-952cUz 7.600 8.540 [air]
Empty utterance: uwb-atcc_ACCU-OvZN8g_001321_001433 uwb-atcc_ACCU-OvZN8g 13.210 14.330 [ground]
Empty utterance: uwb-atcc_TWR-v1sw0a_002796_002867 uwb-atcc_TWR-v1sw0a 27.960 28.670 [air]
Empty utterance: uwb-atcc_TWR-q2wbS3_000336_000419 uwb-atcc_TWR-q2wbS3 3.360 4.190 [air]
Empty utterance: uwb-atcc_TWR-ZfmGUj_002451_002578 uwb-atcc_TWR-ZfmGUj 24.510 25.780 [ground]
Empty utterance: uwb-atcc_TWR-VIKx0e_000309_000408 uwb-atcc_TWR-VIKx0e 3.090 4.080 [air]
Empty utterance: uwb-atcc_TWR-JfoHJv_000234_000308 uwb-atcc_TWR-JfoHJv 2.340 3.080 [air]
Empty utterance: uwb-atcc_APP-O8f26B_000225_000353 uwb-atcc_APP-O8f26B 2.260 3.530 [air]
Empty utterance: uwb-atcc_ACCU-FVpUok_000535_000633 uwb-atcc_ACCU-FVpUok 5.350 6.330 [air]
Empty utterance: uwb-atcc_TWR-jBaOYB_000549_000906 uwb-atcc_TWR-jBaOYB 5.490 9.060 [air]
Empty utterance: uwb-atcc_TWR-jBaOYB_001009_001329 uwb-atcc_TWR-jBaOYB 10.090 13.290 [ground]
Empty utterance: uwb-atcc_TWR-jBaOYB_001398_001537 uwb-atcc_TWR-jBaOYB 13.980 15.370 [air]
Empty utterance: uwb-atcc_APP-Q1M9yF_005349_005423 uwb-atcc_APP-Q1M9yF 53.490 54.230 [air]
there were 492 empty or blank utterances
printing the text file in: experiments/data/uwb_atcc/prep/text2_raw_spk
printing the text and tags file in: experiments/data/uwb_atcc/prep/utt2speakerid
printing the TRAIN SET IDS file in: experiments/data/uwb_atcc/train/ids
printing the TEST SET IDS file in: experiments/data/uwb_atcc/test/ids
creating the train folder:
creating the test folder:
UWB-ATCC corpus was sucessfully created

**Comment by JuanPZuluaga** [comment]
Wow, I'm happy it worked :-) 
- It is expected, not all samples have a transcripts. 
 I'll update that part of the code right now!
 
 Thanks for this. 
 I'm closing this, feel free to open it again.

**Comment by damnfarooq** [comment]
I am having this problem can you help me fix this issue?

(Farooq_thesis) phd-research@phd-research:~/research_space/w2v2-air-traffic$ bash src/run_eval_model.sh


*** About to evaluate a Wav2Vec 2.0 model***
*** Dataset in: experiments/data/uwb_atcc/test ***
*** Output folder: experiments/results/baselines/wav2vec2-large-960h-lv60-self/uwb_atcc/0.0ld_0.05ad_0.05attd_0.0fpd_0.075mtp_12mtl_0.075mfp_12mfl/output ***
Integrating a LM by shallow fusion, results should be better
*** Loading the Wav2Vec 2.0 model, loading... ***
Error. Models were not found in experiments/results/baselines/wav2vec2-large-960h-lv60-self/uwb_atcc/0.0ld_0.05ad_0.05attd_0.0fpd_0.075mtp_12mtl_0.075mfp_12mfl/checkpoint-10000
Traceback (most recent call last):
  File "/home/phd-research/research_space/w2v2-air-traffic/src/eval_model.py", line 250, in <module>
    main()
  File "/home/phd-research/research_space/w2v2-air-traffic/src/eval_model.py", line 152, in main
    processor, processor_ctc_kenlm, model = get_kenlm_processor(path_model, path_lm)
  File "/home/phd-research/research_space/w2v2-air-traffic/src/eval_model.py", line 56, in get_kenlm_processor
    vocab = processor.tokenizer.convert_ids_to_tokens(
UnboundLocalError: local variable 'processor' referenced before assignment

**Comment by damnfarooq** [comment]
This is the output from previous command, I got stuck in run_eval_model.sh now

(Farooq_thesis) phd-research@phd-research:~/research_space/w2v2-air-traffic$ bash /home/phd-research/research_space/w2v2-air-traffic/src/run_train_kenlm.sh


*** About to start the KenLM ***
*** Dataset name: uwb_atcc ***
*** Output folder: experiments/data/uwb_atcc/train/lm ***
uwb_atcc experiments/data/uwb_atcc/train/text

Exporting dataset to text file experiments/data/uwb_atcc/train/lm/4_corpus.txt...
lmplz -o 4 --text experiments/data/uwb_atcc/train/lm/4_corpus.txt --arpa experiments/data/uwb_atcc/train/lm/uwb_atcc_4g_no_fix.arpa
=== 1/5 Counting and sorting n-grams ===
Reading /home/phd-research/research_space/w2v2-air-traffic/experiments/data/uwb_atcc/train/lm/4_corpus.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 113301 types 1766
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:21192 2:2261260544 3:4239863552 4:6783781888
Statistics:
1 1765 D1=0.595645 D2=0.962202 D3+=1.62725
2 16099 D1=0.732908 D2=1.05218 D3+=1.47953
3 38208 D1=0.799969 D2=1.12127 D3+=1.28138
4 60883 D1=0.823461 D2=1.16559 D3+=1.23074
Memory estimate for binary LM:
type      kB
probing 2387 assuming -p 1.5
probing 2712 assuming -r models -p 1.5
trie     950 without quantization
trie     472 assuming -q 8 -b 8 quantization 
trie     895 assuming -a 22 array pointer compression
trie     418 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:21180 2:257584 3:764160 4:1461192
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 4/5 Calculating and writing order-interpolated probabilities ===
Chain sizes: 1:21180 2:257584 3:764160 4:1461192
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 5/5 Writing ARPA model ===
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Name:lmplz      VmPeak:13164676 kB      VmRSS:9084 kB   RSSMax:2609216 kB       user:0.196349   sys:0.464826    CPU:0.661188     real:0.647472
corrected Ken LM in experiments/data/uwb_atcc/train/lm/uwb_atcc_4g.arpa
build_binary trie experiments/data/uwb_atcc/train/lm/uwb_atcc_4g.arpa experiments/data/uwb_atcc/train/lm/uwb_atcc_4g.binary
Reading experiments/data/uwb_atcc/train/lm/uwb_atcc_4g.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Identifying n-grams omitted by SRI
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Writing trie
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
SUCCESS
done doing training of KenLM 
 check the output folder: experiments/data/uwb_atcc/train/lm
Done training 4-gram in experiments/data/uwb_atcc/train/lm

**Comment by JiweiTian** [comment]
The same issue with sarranetor:
I extracted the uwb_atcc database ens extracted it in ZCU_CZ_ATC, putting wav file in audio folder and others in transcripts folder. I run the bash script:

bash data/databases/uwb_atcc/data_prepare_uwb_atcc_corpus.sh

there were 0 empty or blank utterances
printing the text file in: experiments/data/uwb_atcc/prep/text2_raw_spk
printing the text and tags file in: experiments/data/uwb_atcc/prep/utt2speakerid

Traceback (most recent call last):
File "data/utils/gen_train_test.py", line 61, in
main()
File "data/utils/gen_train_test.py", line 42, in main
x_train, x_test = train_test_split(
File "/home/liv/Developer/venv3.8-tf2/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2562, in train_test_split
n_train, n_test = _validate_shuffle_split(
File "/home/liv/Developer/venv3.8-tf2/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 2236, in _validate_shuffle_split
raise ValueError(
ValueError: With n_samples=0, test_size=None and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.
